### ISSUE TITLE
Impossible to set CNAME on zone root

### ISSUE THREAD

**Issue by petrmvala** [hashicorp/terraform-provider-dns#111]
### Terraform Version
Terraform v0.12.24
provider.dns: version = "~> 2.2"

### Affected Resource(s)
- dns_cname_record

### Terraform Configuration Files
```hcl
resource "dns_cname_record" "this" {
  zone   = "example.com."
  name  = ""
  cname = "aws.loadbalancer.dns.name."
}
```

### Expected Behavior
I know "name" is required. Consider following situation:
I have configured dynamic DNS zone `example.com` and I have keys to this zone. I am regularly deploying environments under this zone with DNS names like `dev.example.com` or `uat.example.com`. Configuration for these cases is simple.

However, for my production environment I'd like to use the zone `example.com`. So, what do I put in the dns_cname_record? I don't manage `com` zone and my SSL certificate has DN `example.com`. It is very useful to use the zone root for the production environment, but I can't do that.

### Actual Behavior
Error: DNS record name "name" must not contain whitespace or be empty: ""

### Workaround
Currently I am working around this by requesting a certificate with DN `www.example.com` and using `name = "www"`.

**Comment by tam116** [comment]
The DNS spec doesn't allow a CNAME for a zone root per https://tools.ietf.org/html/rfc1912#section-2.4

Many DNS providers (like Cloudflare or AWS Route 53) have the concept of an ALIAS record that achieves what you want but setting those usually requires special API. Your own DNS provider may have ALIAS records but you can't use this provider to set them. You would need to do so manually or through your providers API (if they have one)

**Comment by petrmvala** [comment]
Ah, shoot! You're right, I haven't realized that. Thanks for the reply.
