### ISSUE TITLE
Create permanent terraform.io TXT record for testing

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-provider-dns#112]
`TestAccDataDnsTxtRecordSet_Basic` does a real-world check of the TXT records for the terraform.io domain, as pointed out in #106. This causes the test to fail whenever these change.

Add a permanent TXT record for testing this functionality, or perhaps use another domain where we have full control over the TXT records.

**Comment by kmoe** [comment]
This is also true for the CNAME test, `TestAccDataDnsCnameRecordSet_Basic`. We probably want to consider dedicated infra for testing this provider.

**Comment by bflad** [comment]
The Terraform team does have `hashicorptest.com` available for use in CloudFlare and managed via Terraform (Cloud). Happy to pick this up so we can get consistent testing. 😄  If/when testing changes are made, I can also add some comments for future travelers about record management there.
