### ISSUE TITLE
retry option for data sources

### ISSUE THREAD

**Issue by muang0** [hashicorp/terraform-provider-dns#114]
Hi all, I am posting here to gauge interest in a potential feature.

**Our use case:** We are creating a load balancer via k8s ingress controller, and need to use its a record set in the same module.  The record takes time to propagate, which leads to an unresolved error.

I am thinking-- could we add an argument to the data source to retry the dns resolution over a specified period?

--Thanks for the response! :smile:

**Comment by shashiverma19** [comment]
We can use local exec with sleep to wait for specified time. 
However that does not guarantee that ALB A record will be available within that time frame. 

How to wait and retry until data source is available ??

**Comment by jroden** [comment]
Could have as another arg, or even ```-1``` value for retry time arg.  Just thinking out loud here.

And yes, local exec could work-- but the downside in my mind is that its a less _clean_ solution, and adds reliance outside terraform since local exec would run on the native system.
