### ISSUE TITLE
Updating records on two different servers at the same time

### ISSUE THREAD

**Issue by fatihbm** [hashicorp/terraform-provider-dns#117]
Hi all, 

I have two bind9 servers and these servers haven't any relation. each server owns an authoritative DNS server role and these servers serve the same DNS zone. So if you wanna a DNS query to any server you can get the same response. 

The problem I have is that I have to update the DNS records on both servers separately.
I tried the following to avoid doing this;

```javascript
provider "dns" {
  update {
    server        = "192.168.0.1"
    key_name      = "zonea-key."
    key_algorithm = "hmac-md5"
    key_secret    = "P25P140u18hbddqNqjHFdA=="
  }
}

provider "dns" {
  alias = "bdbd2"
  update {
    server        = "192.168.1.1"
    key_name      = "zonea-key."
    key_algorithm = "hmac-md5"
    key_secret    = "P25P140u18hbddqNqjHFdA=="
  }
}


resource "dns_a_record_set" "www" {
  zone = "example.com."
  name = "w2"
  addresses = [
    "192.168.3.2",
    "192.168.3.3",
  ]
  ttl = 300
}

resource "dns_a_record_set" "www" {
  provider = dns.bdbd2
  zone = "example.com."
  name = "w2"
  addresses = [
    "192.168.3.2",
    "192.168.3.3",
  ]
  ttl = 300
}
```
Finally, I get the following error. I couldn't understand where is wrong 
```
$ terraform plan

Error: Duplicate resource "dns_a_record_set" configuration

  on main.tf line 31:
  31: resource "dns_a_record_set" "www" {

A dns_a_record_set resource named "www" was already declared at
main.tf:21,1-34. Resource names must be unique per type in each module.


Error: Duplicate provider configuration

  on providers.tf line 11:
  11: provider "dns" {

A provider configuration for "DNS" with alias "bdbd2" was already given at
main.tf:10,1-15. Each configuration for the same provider must have a distinct
alias.
```

I want to say that I am a new user for terraform.
I may have used the wrong method can you give me advice?

versions, Terraform v0.13.0 + provider registry.terraform.io/hashicorp/dns v3.0.0

**Comment by bodgit** [comment]
The error message is telling you exactly what the problem is, you've used the same resource name for both www records:
```
resource "dns_a_record_set" "www" {
...
resource "dns_a_record_set" "www" {
...
```
You need to use different names:
```
resource "dns_a_record_set" "www1" {
...
resource "dns_a_record_set" "www2" {
...
```
The second error suggests you've declared two DNS providers with the same alias in providers.tf and main.tf.
