### ISSUE TITLE
Terraform apply fails with Error: update server is not set

### ISSUE THREAD

**Issue by zayanic** [hashicorp/terraform-provider-dns#124]
I`m creating a cname record set, but when i put the command "terraform apply", i got this message "Error: update server is not set".
I`m using Terraform v0.14.7
In the Azure Plataform in the "DNS ZONES" i have already created a zone called tech.com.br
Anyone could help me ? What should i do ?

provider "azurerm" {
  features {}
}

resource "dns_cname_record" "foo" {
  zone  = "tech.com.br." 
  name  = "foo"
  cname = "info.tech.com.br."
  ttl   = 3600
}

**Comment by bodgit** [comment]
The azure provider has its own resources for managing DNS entries, see https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dns_cname_record
