### ISSUE TITLE
Remote Execution of SRV-DataSource is broken on Terraform Cloud (AWS?)

### ISSUE THREAD

**Issue by marrau** [hashicorp/terraform-provider-dns#188]
### Terraform CLI and Provider Versions

Terraform 1.1.6

{
      source = "hashicorp/dns"
      version = "3.2.1"
}

### Terraform Configuration

```terraform
terraform {
    cloud {
      organization = "<yourcompany>"

      workspaces {
        name = "testdns"
      }
  }

  required_providers {
    dns = {
      source = "hashicorp/dns"
      version = "3.2.1"
    }
  }
}

# fetch all the SRV records to get the actual hostnames of the clusters
data "dns_srv_record_set" "srv_ip" {
  service = "_sip._udp.sip.voice.google.com."
}

output "srv_set" {
  value = data.dns_srv_record_set.srv_ip
}
```

### Expected Behavior

The same output as on a local system (without terraform cloud setup or cloud-workspace in local-mode):

`Changes to Outputs:
  + srv_set = {
      + id      = "_sip._udp.sip.voice.google.com."
      + service = "_sip._udp.sip.voice.google.com."
      + srv     = [
          + {
              + port     = 5060
              + priority = 10
              + target   = "sip-anycast-1.voice.google.com."
              + weight   = 1
            },
          + {
              + port     = 5060
              + priority = 20
              + target   = "sip-anycast-2.voice.google.com."
              + weight   = 1
            },
        ]
    }`

### Actual Behavior

╷
│ Error: error looking up SRV records for "_sip._udp.sip.voice.google.com.": lookup _sip._udp.sip.voice.google.com. on 127.0.0.53:53: cannot unmarshal DNS message
│ 
│   with data.dns_srv_record_set.srv_ip,
│   on dns.tf line 19, in data "dns_srv_record_set" "srv_ip":
│   19: data "dns_srv_record_set" "srv_ip" {
│ 
╵

### Steps to Reproduce

1. You need a terraform cloud account and replace organization name (<yourcompany>) in test code above
2. `terraform init`
3. `terraform apply`

### How much impact is this issue causing?

High

### Logs

https://gist.github.com/marrau/7a707c6fe9a8ae46528ea7bf5c82df71

### Additional Information

- Tested with a normal A-Record-Lookup - works, so only SRV-Records
- Contacted Hashicorp Support - Pointed out that TF-Cloud is running on AWS - so looks like an AWS-Issue with SRV-Records
- There is no way to configure an alternative DNS-Server for DataSources to mitigate Issues with a local resolver

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AaronFriel** [comment]
I may have good news, I'd root caused this and worked with the Go team to ensure this was released & backported to Go 1.17 and 1.16, just need to update and rebuild on those versions: https://github.com/golang/go/issues/51127

If the provider is updated to build with those versions of Go it ought to solve your issue.

**Comment by bflad** [comment]
Hi @marrau 👋 Does using version 3.2.2 or 3.2.3 of the DNS provider resolve this issue? If not, we can look into updating this provider to the recent Go 1.19 release, which will enable EDNS and allow larger DNS packets in certain scenarios.

**Comment by marrau** [comment]
Hi @bflad, i tested it with the mentioned Versions and also with the one given in the Description. 
It´s now working as expected, but i cannot reproduce the error anymore using the old Versions. Maybe a Terraform Update? or some other changes on AWS?
