### ISSUE TITLE
Error updating DNS record: checksum mismatch

### ISSUE THREAD

**Issue by Guigouu** [hashicorp/terraform-provider-dns#213]
### Terraform CLI and Provider Versions

```
Error: Error updating DNS record: checksum mismatch. Computed: fd6a7726dc2e655f282121dc, Contained in token: da7336692730e9cc8d8b55ca

  with module.MMGNA08E5.dns_a_record_set.dns_a[0],
  on .terraform/modules/MMGNA08E5/nic_configuration.tf line 110, in resource "dns_a_record_set" "dns_a":
 110: resource "dns_a_record_set" "dns_a" {
```

### Terraform Configuration

```terraform
DNS provider: v3.2.3
Terraform: 1.1.7
```

### Expected Behavior

No error returned

### Actual Behavior

Error: Error updating DNS record: checksum mismatch

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

Medium

### Additional Information

During the execution stack, the DNS record is **well created** but this error appear resulting a failed of all resources dependencies.

I am using a valid kerberos token with administrator right.

For now, I do not see how to by pass this result.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Minizinger** [comment]
I'm getting the same error while trying to create A or TXT record on windows DNS server. Records themselves are created with no issues, but this error prevents terraform from creating a state file.

**Comment by danielosa** [comment]
Same here, record is created but checksum mismatch error is thrown

**Comment by delaosa** [comment]
now It's working for me, as silly as it may sound the problem was the dns server value was in uppercase,  just using lowercase did the trick.

**Comment by danielosa** [comment]
now It's working for me, as silly as it may sound the problem was the dns server value was in uppercase, just using lowercase did the trick.

**Comment by Guigouu** [comment]
@danielosa Thank you ! Put the DNS server in lowercase with terraform 1.3, avoided to use a kerberos generated with a svc username did the trick I am closing the issue.
