### ISSUE TITLE
dns a records without a timestamp

### ISSUE THREAD

**Issue by Tom-Mann** [hashicorp/terraform-provider-dns#46]
Hi there,

using dns_a_record_set creates a dns record successfully however it creates a record set with a timestamp.  I can't see any option to create the record with a specified timestamp or for it to be set blank\empty, the issue with this is the dns scavenging will clean up these records for things like load balancers if no update is given.
https://social.technet.microsoft.com/wiki/contents/articles/21724.how-dns-aging-and-scavenging-works.aspx

Feature request to add a timestamp option.

**Comment by bodgit** [comment]
The timestamp is an internal Windows property; every dynamic record created gets one. The article you linked to has itself a link showing how to convert a dynamic record to a static one, (i.e. a timestamp of 0):

https://social.technet.microsoft.com/wiki/contents/articles/21726.how-to-convert-a-dynamic-resource-record-to-a-static-one-without-re-creating-it-in-dns.aspx

And it's done by basically using the DNS Manager GUI tool, i.e. out of band of the dynamic DNS protocol (RFC 2136). AFAIK there's no provision in the DNS protocol to supply this timestamp.

AIUI Windows machines continually refresh/update their own DNS records even if the records already exist; the theory being if the machine disappears it won't refresh its DNS and the records then get eventually culled by the scavenging. This works counter to how Terraform manages DNS; if the record exists then Terraform doesn't do anything.

I don't think there's anything you can do here apart from disable scavenging.

**Comment by bookshelfdave** [comment]
There's nothing for us to do here as the Windows API doesn't support this feature. I'm closing this issue out unless there's a new way to go about resolving this issue.
