### ISSUE TITLE
Cannot delete DNS NS record set

### ISSUE THREAD

**Issue by jhogenlids** [hashicorp/terraform-provider-dns#95]
#34 # Terraform Version
Terraform v0.12.6

### Affected Resource(s)
Please list the resources as a list, for example:
"dns_ns_record_set"

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "dns_ns_record_set" "this" {
  zone = "sandstone.online."
  name = "prod"
  nameservers = [
    "ns-x.awsdns-00.com.",
    "ns-xxxx.awsdns-00.org.",
    "ns-xxxx.awsdns-00.co.uk.",
    "ns-xxxx.awsdns-00.net.",
  ]
  ttl = 300
}
```
I added that above without coding the provider as DNS
```hcl
provider "dns" {
  version = "~> 2.2"
}
```
- Terraform plan show it will create the resource
- Terraform apply > yes
- It successfully created the resource but can't find it anywhere in AWS
- Then encountered an error:
Error: update server is not set
- Added this line
```hcl
provider "dns" {
  version = "~> 2.2"
  update {
    server        = "10.97.6.80"
  }
}
```
- Delete the entry
```hcl
resource "dns_ns_record_set" "this" {
  zone = "sandstone.online."
  name = "prod"
  nameservers = [
    "ns-x.awsdns-00.com.",
    "ns-xxxx.awsdns-00.org.",
    "ns-xxxx.awsdns-00.co.uk.",
    "ns-xxxx.awsdns-00.net.",
  ]
  ttl = 300
}
```
- New error:
Error: Error deleting DNS record: 9 (NOTAUTH)

**Comment by kmoe** [comment]
Thanks for the report. It's not clear to me what the sequence of steps was here:

> It successfully created the resource but can't find it anywhere in AWS
> Then encountered an error:
> Error: update server is not set

Did you run an additional command before receiving the error "update server is not set", or was this shown after running `terraform apply`?

**Comment by bflad** [comment]
Closing due to lack of response.
